list.files(pattern = "Rmd")
list.files(pattern = "html")
library(rmarkdown)
library(bslib)
rmarkdown::render_site("index.Rmd")
rmarkdown::render_site("about.Rmd")
rmarkdown::render_site("misc.Rmd")
rmarkdown::render_site("boxplot.Rmd")
rmarkdown::render_site("rants.Rmd")
rmarkdown::render_site("code.Rmd")
rmarkdown::render_site("social.Rmd")
rmarkdown::render_site("work.Rmd")
rmarkdown::render_site("pulse.Rmd")
rmarkdown::render_site("mtrx.Rmd")
rmarkdown::render_site("vegan.Rmd")
rmarkdown::render_site("Rmaps.Rmd")
rmarkdown::render_site("profiles.Rmd")
rmarkdown::render_site("showpal.Rmd")
rmarkdown::render_site("xrdml.Rmd")
rmarkdown::render_site("hydrus_nod_inf.Rmd")
rmarkdown::render_site("kmlconv.Rmd")
rmarkdown::render_site("Google-kml-R.Rmd")
rmarkdown::render_site("georef_jpeg_map.Rmd")
rmarkdown::render_site("Shapefiles-in-R-maps.Rmd")
rmarkdown::render_site("images.Rmd")
rmarkdown::render_site("batch-image-resize.Rmd")

# rants
rmarkdown::render_site("profmetal.Rmd")

# code for learning and teaching
rmarkdown::render_site("teaching.Rmd")
rmarkdown::render_site("WhatsR.Rmd")
rmarkdown::render_site("Rbasics.Rmd")
rmarkdown::render_site("Rgraphs.Rmd")
rmarkdown::render_site("transformR.Rmd")
rmarkdown::render_site("meansR.Rmd")
rmarkdown::render_site("relationR.Rmd")
rmarkdown::render_site("geostats.Rmd")
rmarkdown::render_site("timeseries.Rmd")

# ebook chapters?
rmarkdown::render_site("summtables.Rmd")
rmarkdown::render_site("mapscode.rmd")
rmarkdown::render_site("EDAcode.rmd")
rmarkdown::render_site("CoDAcode.Rmd")
rmarkdown::render_site("soilcode.Rmd")
rmarkdown::render_site("filecode.Rmd")
rmarkdown::render_site("biolcode.Rmd")

rmarkdown::render_site("compositional_Pt0-Intro.rmd")
rmarkdown::render_site("compositional_Pt1-PCA.rmd")

rmarkdown::render_site("testpage.Rmd")
